CREATE TABLE IF NOT EXISTS nuts (
    id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    item_code VARCHAR(50) NOT NULL UNIQUE,
    item_name VARCHAR(100) NOT NULL,
    description TEXT,
    s3_image_name VARCHAR(500),
    total_quantity DECIMAL(10,2),
    quantity_unit VARCHAR(50),
    price DECIMAL(10, 2),
    in_stock BOOLEAN NOT NULL DEFAULT TRUE,
    created_tsp TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_tsp TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(100),
    updated_by VARCHAR(100)
);
