UPDATE pooja_items
SET description = v.description
FROM (
    VALUES
    ('ADDU_THERA', 'Traditional ceremonial screen cloth used during Telugu wedding rituals.'),
    ('AKSHINTHALU', 'Sacred rice mixed with turmeric used for blessings in Hindu ceremonies.'),
    ('BANANA', 'Fresh bananas used for pooja rituals and traditional ceremonies.'),
    ('BANANA_GELALU', 'Banana stem pieces used for decoration and ritual purposes.'),
    ('BANGLES', 'Traditional decorative bangles worn during weddings and auspicious occasions.'),
    ('BASIKAALU', 'Traditional wedding ornament tied to bride and groom during ceremony.'),
    ('BETEL_LEAVES', 'Fresh betel leaves used in pooja rituals and offerings.'),
    ('BLOUSE_PIECES', 'Blouse fabric pieces offered as part of traditional gifts.'),
    ('CANE_BASKET', 'Handwoven cane basket used for holding pooja items.'),
    ('CHANDAN_POWDER', 'Sandalwood powder used for religious markings and rituals.'),
    ('CLAY_POTS', 'Earthen clay pots used in traditional ceremonies and cooking.'),
    ('COCONUT_DECOR', 'Decorated coconut used for auspicious rituals.'),
    ('COCONUTS', 'Whole coconuts used in pooja and Hindu ceremonies.'),
    ('COTTON_WICKS', 'Cotton wicks used for lighting oil lamps during pooja.'),
    ('COW_MILK', 'Fresh cow milk used in abhishekam and rituals.'),
    ('CURD', 'Fresh curd used in traditional rituals and offerings.'),
    ('DECORATIVE_BINDELU', 'Decorative pots used for ceremonial and festive occasions.'),
    ('DHANYAM', 'Grains used in rituals symbolizing prosperity and abundance.'),
    ('DIYAS', 'Traditional oil lamps used during pooja and festivals.'),
    ('FLOWER_GARLANDS', 'Fresh flower garlands used for deity decoration and weddings.'),
    ('FLOWERS', 'Fresh flowers used for pooja and decorations.'),
    ('FRUITS', 'Seasonal fruits offered during religious ceremonies.'),
    ('GHEE', 'Clarified butter used for lamps and ritual offerings.'),
    ('GODUMA_RAAYI', 'Wheat grains used in traditional rituals.'),
    ('HONEY', 'Pure honey used in abhishekam and offerings.'),
    ('IKKILLIPERLU', 'Traditional ritual seeds used in Telugu ceremonies.'),
    ('INCENSE_STICKS', 'Fragrant incense sticks used during pooja rituals.'),
    ('JAGGERY', 'Natural jaggery used in naivedyam and rituals.'),
    ('JEELAKARRA_BELLAM', 'Cumin and jaggery mixture used in Telugu wedding rituals.'),
    ('KARAKKAYALU', 'Sacred dried fruits used in traditional ceremonies.'),
    ('KARPOORAM', 'Camphor used for aarti during pooja.'),
    ('KUMKUDUKAYA', 'Soapnut used in traditional purification rituals.'),
    ('KUMKUM', 'Sacred red powder used for tilak and pooja.'),
    ('MANGO_LEAVES', 'Fresh mango leaves used for toran and ritual decoration.'),
    ('MATCH_BOXES', 'Matchboxes used for lighting lamps and incense.'),
    ('MUTHYALA_THALAMBRALU', 'Pearl mixed sacred rice used in Telugu wedding rituals.'),
    ('NAVA_DHANYALU', 'Nine sacred grains used in Hindu rituals.'),
    ('OIL', 'Oil used for lighting lamps and ceremonial purposes.'),
    ('PAGADAM', 'Traditional coral ornament used in ceremonies.'),
    ('PARANI', 'Decorative ritual item used in auspicious ceremonies.'),
    ('PUFFED_RICE', 'Puffed rice used in offerings and rituals.'),
    ('RICE', 'Raw rice used for rituals and offerings.'),
    ('ROLLU', 'Traditional grinding stone used in ceremonial rituals.'),
    ('ROLLU_ROKALI', 'Traditional grinding stone set used in weddings.'),
    ('TENDER_COCONUT', 'Tender coconut used for offerings and rituals.'),
    ('TURMERIC', 'Turmeric powder used for purification and rituals.'),
    ('TURMERIC_BULLETS', 'Whole dried turmeric roots used in ceremonies.'),
    ('UBTAN', 'Herbal ceremonial paste applied during wedding rituals.'),
    ('WHITE_THREAD', 'Sacred white thread used in religious ceremonies.')
) AS v(code, description)
WHERE pooja_items.item_code = v.code;