
CREATE TABLE IF NOT EXISTS occasions (
    id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    occasion_code VARCHAR(50) NOT NULL UNIQUE,
    occasion_name VARCHAR(100) NOT NULL,
    description TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_tsp TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_tsp TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(100),
    updated_by VARCHAR(100)
);
