
-- Add columns to pooja_items
ALTER TABLE pooja_items 
ADD COLUMN IF NOT EXISTS image_url VARCHAR(500),
ADD COLUMN IF NOT EXISTS video_url VARCHAR(500),
ADD COLUMN IF NOT EXISTS poster_url VARCHAR(500),
ADD COLUMN IF NOT EXISTS price DECIMAL(10, 2);

-- Add columns to occasions
ALTER TABLE occasions 
ADD COLUMN IF NOT EXISTS image_url VARCHAR(500),
ADD COLUMN IF NOT EXISTS video_url VARCHAR(500),
ADD COLUMN IF NOT EXISTS poster_url VARCHAR(500),
ADD COLUMN IF NOT EXISTS price DECIMAL(10, 2),
ADD COLUMN IF NOT EXISTS type VARCHAR(50);
