-- Update S3 image names (store only image file name)

-- Insert pooja items with default quantity = 0

INSERT INTO pooja_items
(item_code, item_name, s3_image_name, total_quantity, quantity_unit, price, in_stock, created_by)
VALUES

('ADDU_THERA', 'Addu Thera', 'addu_thera.png', 0, 'piece', 0, true, 'SYSTEM'),
('AKSHINTHALU', 'Akshinthalu', 'akshinthalu.png', 0, 'packet', 0, true, 'SYSTEM'),
('BANANA', 'Banana', 'banana.png', 0, 'dozen', 0, true, 'SYSTEM'),
('BANANA_GELALU', 'Banana Gelalu', 'banana_gelalu.png', 0, 'set', 0, true, 'SYSTEM'),
('BANGLES', 'Bangles', 'bangles.png', 0, 'set', 0, true, 'SYSTEM'),
('BASIKAALU', 'Basikaalu', 'basikaalu.png', 0, 'pair', 0, true, 'SYSTEM'),
('BETEL_LEAVES', 'Betel Leaves', 'betel_leaves.png', 0, 'bundle', 0, true, 'SYSTEM'),
('BLOUSE_PIECES', 'Blouse Pieces', 'blouse_pieces.png', 0, 'piece', 0, true, 'SYSTEM'),
('CANE_BASKET', 'Cane Basket', 'cane_basket.png', 0, 'piece', 0, true, 'SYSTEM'),
('CHANDAN_POWDER', 'Chandan Powder', 'chandan_powder.png', 0, 'packet', 0, true, 'SYSTEM'),
('CLAY_POTS', 'Clay Pots', 'clay_pots.png', 0, 'piece', 0, true, 'SYSTEM'),
('COCONUT_DECOR', 'Coconut Decor', 'coconut_decor.png', 0, 'piece', 0, true, 'SYSTEM'),
('COCONUTS', 'Coconuts', 'coconuts.png', 0, 'piece', 0, true, 'SYSTEM'),
('COTTON_WICKS', 'Cotton Wicks', 'cotton_wicks.png', 0, 'packet', 0, true, 'SYSTEM'),
('COW_MILK', 'Cow Milk', 'cow_milk.png', 0, 'litre', 0, true, 'SYSTEM'),
('CURD', 'Curd', 'curd.png', 0, 'litre', 0, true, 'SYSTEM'),
('DECORATIVE_BINDELU', 'Decorative Bindelu', 'decorative_bindelu.png', 0, 'piece', 0, true, 'SYSTEM'),
('DHANYAM', 'Dhanyam', 'dhanyam.png', 0, 'kg', 0, true, 'SYSTEM'),
('DIYAS', 'Diyas', 'diyas.png', 0, 'piece', 0, true, 'SYSTEM'),
('FLOWER_GARLANDS', 'Flower Garlands', 'flower_garlands.png', 0, 'piece', 0, true, 'SYSTEM'),
('FLOWERS', 'Flowers', 'flowers.png', 0, 'kg', 0, true, 'SYSTEM'),
('FRUITS', 'Fruits', 'fruits.png', 0, 'kg', 0, true, 'SYSTEM'),
('GHEE', 'Ghee', 'ghee.png', 0, 'litre', 0, true, 'SYSTEM'),
('GODUMA_RAAYI', 'Goduma Raayi', 'goduma_raayi.png', 0, 'kg', 0, true, 'SYSTEM'),
('HONEY', 'Honey', 'honey.png', 0, 'bottle', 0, true, 'SYSTEM'),
('IKKILLIPERLU', 'Ikkilliperlu', 'ikkilliperlu.png', 0, 'packet', 0, true, 'SYSTEM'),
('INCENSE_STICKS', 'Incense Sticks', 'incense_sticks.png', 0, 'packet', 0, true, 'SYSTEM'),
('JAGGERY', 'Jaggery', 'jaggery.png', 0, 'kg', 0, true, 'SYSTEM'),
('JEELAKARRA_BELLAM', 'Jeelakarra Bellam', 'jeelakarra_bellam.png', 0, 'set', 0, true, 'SYSTEM'),
('KARAKKAYALU', 'Karakkayalu', 'karakkayalu.png', 0, 'packet', 0, true, 'SYSTEM'),
('KARPOORAM', 'Karpooram', 'karpooram.png', 0, 'packet', 0, true, 'SYSTEM'),
('KUMKUDUKAYA', 'Kumkudukaya', 'kumkudukaya.png', 0, 'piece', 0, true, 'SYSTEM'),
('KUMKUM', 'Kumkum', 'kumkum.png', 0, 'packet', 0, true, 'SYSTEM'),
('MANGO_LEAVES', 'Mango Leaves', 'mango_leaves.png', 0, 'bundle', 0, true, 'SYSTEM'),
('MATCH_BOXES', 'Match Boxes', 'match_boxes.png', 0, 'box', 0, true, 'SYSTEM'),
('MUTHYALA_THALAMBRALU', 'Muthyala Thalambralu', 'muthyala_thalambralu.png', 0, 'packet', 0, true, 'SYSTEM'),
('NAVA_DHANYALU', 'Nava Dhanyalu', 'nava_dhanyalu.png', 0, 'set', 0, true, 'SYSTEM'),
('OIL', 'Oil', 'oil.png', 0, 'litre', 0, true, 'SYSTEM'),
('PAGADAM', 'Pagadam', 'pagadam.png', 0, 'piece', 0, true, 'SYSTEM'),
('PARANI', 'Parani', 'parani.png', 0, 'piece', 0, true, 'SYSTEM'),
('PUFFED_RICE', 'Puffed Rice', 'puffed_rice.png', 0, 'kg', 0, true, 'SYSTEM'),
('RICE', 'Rice', 'rice.png', 0, 'kg', 0, true, 'SYSTEM'),
('ROLLU', 'Rollu', 'rollu.png', 0, 'piece', 0, true, 'SYSTEM'),
('ROLLU_ROKALI', 'Rollu Rokali', 'rollu_rokali.png', 0, 'set', 0, true, 'SYSTEM'),
('TENDER_COCONUT', 'Tender Coconut', 'tender_coconut.png', 0, 'piece', 0, true, 'SYSTEM'),
('TURMERIC', 'Turmeric', 'turmeric.png', 0, 'kg', 0, true, 'SYSTEM'),
('TURMERIC_BULLETS', 'Turmeric Bullets', 'turmeric_bullets.png', 0, 'packet', 0, true, 'SYSTEM'),
('UBTAN', 'Ubtan', 'ubtan.png', 0, 'packet', 0, true, 'SYSTEM'),
('WHITE_THREAD', 'White Thread', 'white_thread.png', 0, 'roll', 0, true, 'SYSTEM');
